// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const browser: typeof import('wxt/browser')['browser']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const getShortcutDisplay: typeof import('/home/waverly/workspace/code/front/ai-bookmark-manager/hooks/useKeyboardShortcuts')['getShortcutDisplay']
  const i18n: typeof import('/home/waverly/workspace/code/front/ai-bookmark-manager/components/i18n')['default']
  const i18nConfig: typeof import('/home/waverly/workspace/code/front/ai-bookmark-manager/components/i18nConfig')['default']
  const reducer: typeof import('/home/waverly/workspace/code/front/ai-bookmark-manager/hooks/use-toast')['reducer']
  const storage: typeof import('wxt/storage')['storage']
  const toast: typeof import('/home/waverly/workspace/code/front/ai-bookmark-manager/hooks/use-toast')['toast']
  const useBookmarks: typeof import('/home/waverly/workspace/code/front/ai-bookmark-manager/hooks/use-bookmarks')['useBookmarks']
  const useKeyboardShortcuts: typeof import('/home/waverly/workspace/code/front/ai-bookmark-manager/hooks/useKeyboardShortcuts')['useKeyboardShortcuts']
  const useToast: typeof import('/home/waverly/workspace/code/front/ai-bookmark-manager/hooks/use-toast')['useToast']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ShortcutConfig } from '/home/waverly/workspace/code/front/ai-bookmark-manager/hooks/useKeyboardShortcuts'
  import('/home/waverly/workspace/code/front/ai-bookmark-manager/hooks/useKeyboardShortcuts')
}
